[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-18 16:33:27 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:33:27 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:33:27 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:33:27 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:33:29 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:33:29 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:33:31 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:33:31 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:33:59 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:33:59 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:33:59 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:33:59 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:01 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:01 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:08 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:10 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:10 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:12 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:12 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:14 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:14 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:14 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:14 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:14 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:14 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:16 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:16 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:18 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:18 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:18 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:18 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:34:18 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:34:18 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:37:38 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:37:38 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:37:38 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:37:38 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:37:40 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:37:40 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:37:50 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:37:50 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:37:51 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:37:51 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:50 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:50 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:50 view.tree.model] ERROR select value error: case_type, 
