[2017-08-18 16:46:50 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:50 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:50 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:50 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:50 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:50 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:50 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:50 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:50 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:56 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:56 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:56 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:57 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:57 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:57 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:57 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:57 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:57 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:57 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:57 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:46:57 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:46:57 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:57:49 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:57:49 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 16:57:49 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 16:57:49 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:04:12 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:04:12 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:04:12 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:04:12 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:13:26 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:13:26 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:13:26 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:13:26 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:13:59 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:13:59 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:13:59 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:13:59 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:14:41 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:14:41 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:14:41 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:14:41 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:16:33 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:16:33 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:16:34 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:16:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:20:49 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:20:49 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:20:49 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:20:49 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:26:12 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:26:12 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:26:12 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:26:12 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:28:15 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:28:15 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:28:15 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:28:15 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:33:07 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:33:07 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:33:07 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:33:07 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:33:57 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:33:57 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:33:57 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:33:57 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:33:59 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:33:59 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:35:48 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:35:48 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-18 18:35:48 view.tree.model] ERROR select value error: case_type, 
[2017-08-18 18:35:48 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:14:46 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:14:46 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:14:46 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:14:46 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:14:46 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:14:46 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:14:52 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:14:52 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:14:54 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:14:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:14:59 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:14:59 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:02 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:02 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:02 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:02 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:02 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:02 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:02 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:02 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:02 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:02 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:03 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:03 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:03 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:03 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:03 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:03 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:03 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:03 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:03 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:03 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-21 11:15:03 view.tree.model] ERROR select value error: case_type, 
[2017-08-21 11:15:03 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 259, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u''

[2017-08-24 10:24:32 view.lib.view_def] ERROR 获取字典值失败, None
[2017-08-24 10:24:32 view.lib.view_def] ERROR None

[2017-08-24 10:24:32 view.lib.view_def] ERROR get dict case_type failed.
[2017-08-24 10:24:32 view.lib.view_def] ERROR None

[2017-08-24 10:24:37 view.lib.view_def] ERROR 获取字典值失败, None
[2017-08-24 10:24:37 view.lib.view_def] ERROR None

[2017-08-24 10:24:37 view.lib.view_def] ERROR get dict case_type failed.
[2017-08-24 10:24:37 view.lib.view_def] ERROR None

[2017-08-24 10:34:55 view.lib.view_def] ERROR 获取字典值失败, None
[2017-08-24 10:34:55 view.lib.view_def] ERROR None

[2017-08-24 10:34:55 view.lib.view_def] ERROR get dict case_type failed.
[2017-08-24 10:34:55 view.lib.view_def] ERROR None

[2017-08-24 10:34:59 view.lib.view_def] ERROR 获取字典值失败, None
[2017-08-24 10:34:59 view.lib.view_def] ERROR None

[2017-08-24 10:34:59 view.lib.view_def] ERROR get dict case_type failed.
[2017-08-24 10:34:59 view.lib.view_def] ERROR None

