[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, BATCH_SUIT
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'BATCH_SUIT'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, BATCH_SUIT
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'BATCH_SUIT'

[2017-06-06 14:01:53 view.tree.model] ERROR select value error: case_type, <bound method OrcSelect.get_data of <OrcView.Lib.LibView.OrcSelect object at 0x123e68320>>
[2017-06-06 14:01:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: <bound method OrcSelect.get_data of <OrcView.Lib.LibView.OrcSelect object at 0x123e68320>>

[2017-06-16 17:32:06 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:06 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:06 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:06 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:06 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:06 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:06 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:06 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:08 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:08 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:08 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:08 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:08 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:09 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:09 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:09 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:09 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:09 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:09 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:09 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:09 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:09 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:09 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:32:09 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:32:09 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: 'widget_type'

[2017-06-16 17:34:08 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:34:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-06-16 17:34:08 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:34:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-06-16 17:34:08 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:34:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-06-16 17:34:08 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:34:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-06-16 17:34:10 view.tree.model] ERROR select value error: widget_type, ALERT
[2017-06-16 17:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'ALERT'

[2017-06-16 17:34:10 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-06-16 17:34:10 view.tree.model] ERROR select value error: widget_type, ALERT
[2017-06-16 17:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'ALERT'

[2017-06-16 17:34:10 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-06-16 17:34:10 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-06-16 17:34:10 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-06-16 17:34:10 view.tree.model] ERROR select value error: widget_type, ALERT
[2017-06-16 17:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'ALERT'

[2017-06-16 17:34:10 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-06-16 17:34:10 view.tree.model] ERROR select value error: widget_type, GROUP
[2017-06-16 17:34:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 337, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-08-02 10:32:20 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x121841cf8>'}失败, None
[2017-08-02 10:32:20 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 10:32:20 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'12.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x121841cf8>'}失败, None
[2017-08-02 10:32:20 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 10:32:21 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x121841cf8>'}失败, None
[2017-08-02 10:32:21 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 10:32:21 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'12.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x121841cf8>'}失败, None
[2017-08-02 10:32:21 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 10:34:56 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x12241fcb0>'}失败, None
[2017-08-02 10:34:56 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 10:34:56 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'12.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x12241fcb0>'}失败, None
[2017-08-02 10:34:56 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 10:58:44 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x11aec0cb0>'}失败, None
[2017-08-02 10:58:44 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 10:58:44 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'13.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x11aec0cb0>'}失败, None
[2017-08-02 10:58:44 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:11:52 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x11b1dbcb0>'}失败, None
[2017-08-02 11:11:52 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:11:52 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'18.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x11b1dbcb0>'}失败, None
[2017-08-02 11:11:52 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:12:36 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x11b1dbcb0>'}失败, None
[2017-08-02 11:12:36 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:12:36 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'13.<OrcView.Lib.LibBaseWidget.OrcSelect object at 0x11b1dbcb0>'}失败, None
[2017-08-02 11:12:36 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:20:49 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:20:49 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:20:49 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'13.TEST'}失败, None
[2017-08-02 11:20:49 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:20:50 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:20:50 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:20:50 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'12.TEST'}失败, None
[2017-08-02 11:20:50 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:21:53 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:21:53 view.data.data_src.data_src_list_model] ERROR None

